### ISSUE TITLE
LightStudio error when opening Blender 2.8x

### ISSUE THREAD

**Issue by leomoon** [leomoon-studios/leomoon-lightstudio#23]
Exception ignored in: <function ImagePreviewCollection.del at 0x00000256AB6A4D08>
Traceback (most recent call last):
File "D:\Programs\blender-2.80-windows64\2.80\scripts\modules\bpy\utils\previews.py", line 79, in del
f"{self!r}: left open, remove with "
ResourceWarning: <ImagePreviewCollection id=0x256ab615780[0], <super: <class 'ImagePreviewCollection'>, >>: left open, remove with 'bpy.utils.previews.remove()'

**Comment by leomoon** [comment]
Is fixed in upcoming LightStudio 2.5.0.

**Comment by one0oneChen** [comment]
Hello, I encountered the same problem, what is the reason for this and how did you solve it?

**Comment by leomoon** [comment]
Hi, Please remove the old version from Blender and download the latest zip from this github repo and install it.

Thanks.
