### ISSUE TITLE
addon not found: 'leomoon-lightstudio'

### ISSUE THREAD

**Issue by gerroon** [leomoon-studios/leomoon-lightstudio#26]
Hi

I am trying to use this under 2.83 and this is the erro I get when I try to enable the addon from the addon panel. It shows up there but it is not possible to enable or check the tickbox and throws `addon not found: 'leomoon-lightstudio'` in the terminal when I click on to enable it.

I am using 2.83, Windows 10 x64,LLS 2.5.2

**Comment by leomoon** [comment]
hello, where did you download it from? If you used Github's Code button > Download ZIP, it wouldn't work. The download link is in the description:
https://leomoon.com/downloads/plugins/leomoon-lightstudio/

Please let me know if  that worked for you.

**Comment by gerroon** [comment]
Hi

I downloaded the gihub master.zip. I will try the other download.
