### ISSUE TITLE
Feature Request: multiple profiles active at once

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/leomoon-lightstudio#36]
What:
Make it possible to have several active profiles and not just one.

Why:
LLS is super cool to light a single product. In my case I have a whole world with a lot of products in it. Each product has to have nice lighting. So what I would love to have is the possibility to have several LLS profiles active at the same time. For each product one profile. Unfortunately as soon as I click a profile all the others get unlinked. So this is not feasible for a scene with several products distributed across some space.

Implementation Proposal:
I think for single product lighting it's optimal as it is right now. So I would try to keep that as default. My proposal is to add a simple boolean called something like "multi mode" to the Profiles tab.  It's unchecked by default.  If it is unchecked everything is just like it used to be. As soon as you ceck it, you get the same two buttons known from the light list to disable or isolate each profile. So now if you just click on a profile it should only change the light list and not unlink any profile. Unlinking happens only through disabeling or isolating.

![multi mode prev](https://user-images.githubusercontent.com/9008901/112525698-6f361b00-8da1-11eb-9dd5-9ddb44019e1a.png)

There could also be an extra label above the light list (only if multi mode is active) so it's clear to which light profile the lightlist belongs. Like so:

![LightListWithProfileName](https://user-images.githubusercontent.com/9008901/112527495-66dedf80-8da3-11eb-8c6d-4ac678229100.png)

As an alternative one could also just go without the "multi mode" checkbox and only add the mute and isolate buttons to the profiles. Because you could just click the star icons of the profiles to get the exact same behaviour as it is right now, but you would gain much more flexibility in how to use this awesome addon.

**Comment by leomoon** [comment]
This feature has been added to LeoMoon LightStudio 2.9.0.
