### ISSUE TITLE
Still Cannot Install on 2.93 neither 3.0

### ISSUE THREAD

**Issue by denmod1** [leomoon-studios/leomoon-lightstudio#43]
Hi, it seemed that there was some fix you mentioned recently but I am still not able to install this addon. Am i doing something wrong?

**Comment by leomoon** [comment]
Hi,

We initially had a fix for it but it would only work randomly. We are testing a new fix which will be coming out in a week or so.

**Comment by denmod1** [comment]
Ok looking forward! You guys are on to something with this add-on. Great work!

**Comment by denmod1** [comment]
HI guys any update?

**Comment by leomoon** [comment]
Hello,

Please try downloading the latest version:
https://github.com/leomoon-studios/leomoon-lightstudio/archive/refs/heads/master.zip

Thanks.

**Comment by denmod1** [comment]
Hi, the addon installed fine. Everything seems ok. However, there are no lights to select. Its just not there. Maybe you forgot to add the lights to the package during the update.

**Comment by leomoon** [comment]
Hello,

I used the same link to install it on a fresh Blender 2.93:
![image](https://user-images.githubusercontent.com/3268946/125875053-0b14ce99-bade-493d-9eb6-340911106095.png)

It might be best to delete any previous versions of LightStudio

**Comment by denmod1** [comment]
Hi. Thank you. I got through. I had to turn off "Experimental" Feature in Cycles. That seemed to fix it. Although i turned it back on and it works fine. Not sure. But its working now. Thanks again for your quick replies.
