### ISSUE TITLE
Animated Light Keyframes not showing in timeline

### ISSUE THREAD

**Issue by Aweinberg1** [leomoon-studios/leomoon-lightstudio#45]
The lightstudio keying set can only be found if I go to the action editor and pull up the LLS_ROTATIONAction 
In previous versions the keyframes would directly populate in the timeline.

**Comment by leomoon** [comment]
There's a slight change on how keyframes work. Since the introduction of Basic Light, there are different objects that are being keyed. We are working to add this feature back very soon. :)

**Comment by Aweinberg1** [comment]
Thanks for the work, very appreciated!

**Comment by leomoon** [comment]
In LightStudio version 2.8.2 we had to add a new section called Mode. If you switch from Normal to Animation, then you'll be able to see the keyframes.
![image](https://user-images.githubusercontent.com/3268946/126050580-fa092d18-c361-4293-afcd-4352191c6e55.png)
