### ISSUE TITLE
Copy selected profile buggy with multi profile mode

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/leomoon-lightstudio#49]
First thanks for implementing the multi profile mode. Just tested it an I think it's pretty neat!

Now to the bug:
Copy selected Profile seems to always copie the first  visible profile, not the selected one.

Steps to reproduce
1. Activate multiple profiles
2. Create two different profiles
3. Now try to duplicate profiles:
  - With both visible try to duplicate the second one -> It will have the name of the second one, but it will duplicate the first one
  - With only the one you want to duplicate set to visible -> everything correct
  - With none visible -> Phyton Traceback

**Comment by leomoon** [comment]
Fixed in LightStudio 2.9.1
