### ISSUE TITLE
Light list get cleared on turning off other profiles

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/leomoon-lightstudio#50]
Light list get cleard on turning off other profiles in multi profile mode

Steps to reproduce:

1. Activate multi profile mode
2. create at least two profiles each with some lights
3. Now turn off one profile with the light bulb symbol. Now the light list suddenly is empty, although it looks like you previous profile is still the selected one. Selecting another profile and then select the profile again fixes it.

So i guess internally it selects the one profile you are turning off, then turns it off. Thus the light list gets empty. But visually it still looks like you selected profile hasn't changed.

Possible solutions:
1. The selection automatically gets set to the previous slected profile again. So it's like the just turned off profile never got selected, ofcourse only visually. (I would prefer this solution)
2. The just turned off profile is the selected one, so it's obvious that you have to select the other one again.
Activate multiple profiles

**Comment by leomoon** [comment]
Fixed in LightStudio 2.9.1
