### ISSUE TITLE
Copying lights broken in multi profile mode

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/leomoon-lightstudio#52]
Copying lights has some problems with multi pfrofile mode, too.

It works fine if only the profile is visible in which you want to duplicate a light. But if you have several visible profiles then it will result in a mess. It gets added to the first visible profile, still has the name of the light in the profile it comes from and also rotates around the origin of that profile, but it is listed in the wrong one.

**Comment by leomoon** [comment]
Fixed in LightStudio 2.9.1
