### ISSUE TITLE
Try rotate the view - appear Select Menu

### ISSUE THREAD

**Issue by bondnaruto** [leomoon-studios/leomoon-lightstudio#6]
Can some help me?

If I add Blender Light Studio Add-on
when mouse over objects (2 and more) and i try to rotate the view (Alt+Press Left mouse button) every time appear the window "Select Menu"
If Light Studio is disabled, everything is working fine and window not appear
How I can disabled appear "Select Menu"?

![help](https://cloud.githubusercontent.com/assets/27413443/24998724/cdcc887c-2043-11e7-86d0-61d401f5bfa0.gif)

**Comment by leomoon** [comment]
Rotating the view is done with middle click. Isn't it?

**Comment by bondnaruto** [comment]
As default it work like you write, but in my case Alt+Left Click

**Comment by leomoon** [comment]
We're gonna add that disable override check box with saving very soon.

**Comment by bondnaruto** [comment]
Thanks, and please add checkbox to save these setting as default
