### ISSUE TITLE
Selection through objects

### ISSUE THREAD

**Issue by RowanGryder** [leomoon-studios/leomoon-lightstudio#7]
I found an issue which only comes up when the plugin is enabled. When trying to move an object via the Gizmo, if there is an object behind the gizmo handle it will move that object instead. I made a quick [gif](http://i.imgur.com/QtqKWd5.gifv) but you can clearly see that in the end the centered cube is completely hidden by the selected cube and still it is the center cube that is selected and moved on the Z axis.

**Comment by leomoon** [comment]
I don't see that problem with the latest build. Did you change select object from left mouse click to right mouse click?

**Comment by RowanGryder** [comment]
Nope, I'm using Maya binds for most things aside from a few blender specific things.

EDIT: I also notice that when the plugin is enabled deleting and selecting seem to come up with "custom select/delete" in the tool bar. Not sure if this is directly related but something that might help.

**Comment by leomoon** [comment]
Currently switching the left and right mouse click from Blender default will screw things up. We're working on a fix.

**Comment by RowanGryder** [comment]
Excellent. Thank you guys so much for such a great plugin.
