### ISSUE TITLE
screen.redo_last issue

### ISSUE THREAD

**Issue by brothermechanic** [leomoon-studios/leomoon-lightstudio#9]
Hello
Can you describe BLStudio.selection_overriden checkbox?
i have issue with redo last, please, see video
https://drive.google.com/open?id=1T8tQ4D_JtZdRWc-xdDvI3xUpxY59_A51
i think before this is blender bug, but....)))
Thank you.

**Comment by leomoon** [comment]
That option is when the user changes default mouse selection from right click to left click.
